# Defines the deployment for the tika transformer app
# Details: https://git.alfresco.com/Repository/alfresco-docker-transformers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "content-services.shortname" . }}-tika
  labels:
    {{- include "tika.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tika.replicaCount }}
  selector:
    matchLabels:
      {{- include "tika.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
{{ toYaml .Values.global.strategy.rollingUpdate | indent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-tika.yaml") . | sha256sum }}
      labels:
        {{- include "tika.selectorLabels" . | nindent 8 }}
        {{- with .Values.tika.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "component-pod-security-context" .Values.tika | indent 4 }}
    {{- if .Values.tika.nodeSelector }}
      nodeSelector: {{- .Values.tika.nodeSelector | toYaml | nindent 8 }}
    {{- end }}
      {{- include "alfresco-content-services.imagePullSecrets" . | indent 6 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "content-services.shortname" . }}-tika
              topologyKey: failure-domain.beta.kubernetes.io/zone
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "content-services.shortname" . }}-tika
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.tika.image.repository }}:{{ .Values.tika.image.tag }}"
          imagePullPolicy: {{ .Values.tika.image.pullPolicy }}
          {{- include "component-security-context" .Values.tika | indent 8 }}
          envFrom:
          - configMapRef:
              # config map to use, defined in config-tika.yaml
              name: {{ template "content-services.shortname" . }}-tika-configmap
          - secretRef:
              name: {{ default (printf "%s-brokersecret" (include "content-services.shortname" .)) .Values.messageBroker.existingSecretName }}
          env:
            {{- include "activemq.env" . | nindent 12 }}
          {{- if and (.Values.global.elasticAPM) (.Values.global.elasticAPM.enabled) }}
          - name: ELASTIC_APM_SERVER_URLS
            value: {{ .Values.global.elasticAPM.containers.env.serverUrls }}
          - name: ELASTIC_APM_SERVICE_NAME
            value: "tika"
          - name: ELASTIC_APM_APPLICATION_PACKAGES
            value: com.alfresco,org.alfresco,nl.amsterdam
          - name: ELASTIC_APM_ENVIRONMENT
            value: {{ .Values.global.elasticAPM.containers.env.environment }}
          - name: ELASTIC_APM_LOG_LEVEL
            value: {{ .Values.global.elasticAPM.containers.env.logLevel }}
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.elasticAPM.containers.env.secretToken.name }}
                key: {{ .Values.global.elasticAPM.containers.env.secretToken.key }}
          - name: JAVA_TOOL_OPTIONS
            value: {{ .Values.global.elasticAPM.containers.env.javaToolOptions }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.tika.image.internalPort }}
          resources: {{- toYaml .Values.tika.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.tika.image.internalPort }}
            initialDelaySeconds: {{ .Values.tika.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.tika.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.tika.readinessProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.tika.image.internalPort }}
            initialDelaySeconds: {{ .Values.tika.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.tika.livenessProbe.periodSeconds }}
            failureThreshold: 1
            timeoutSeconds: {{ .Values.tika.livenessProbe.timeoutSeconds }}
          {{- if and (.Values.global.elasticAPM) (.Values.global.elasticAPM.enabled) }}
          volumeMounts:
            - name: {{ .Values.global.elasticAPM.containers.volumeMounts.name }}
              mountPath: {{ .Values.global.elasticAPM.containers.volumeMounts.mountPath }}
          {{- end }}
      {{- if and (.Values.global.elasticAPM) (.Values.global.elasticAPM.enabled) }}
      initContainers:
        - name: elastic-java-agent
          image: {{ .Values.global.elasticAPM.initContainers.image }}
          volumeMounts:
          - mountPath: {{ .Values.global.elasticAPM.initContainers.volumeMounts.mountPath }}
            name: {{ .Values.global.elasticAPM.initContainers.volumeMounts.name }}
          command: ['cp', '-v', '/usr/agent/elastic-apm-agent.jar', '/elastic/apm/agent']
      {{- end }}
      volumes:
      {{- if and (.Values.global.elasticAPM) (.Values.global.elasticAPM.enabled) }}
      - name: elastic-apm-agent
        emptyDir: {}
      {{- end }}
