{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "activemq.fullname" . }}
  labels:
    app: {{ template "activemq.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "activemq.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "activemq.fullname" . }}
        release: {{ .Release.Name }}
    spec:
    {{- include "component-pod-security-context" .Values | indent 4 }}
    {{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
    {{- end }}
      containers:
      - name: activemq
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- include "component-security-context" .Values | indent 6 }}
        env:
        - name: ACTIVEMQ_CONFIG_MINMEMORY
          value: "{{ .Values.resources.requests.memory | replace "Mi" "" }}"
        - name: ACTIVEMQ_CONFIG_MAXMEMORY
          value: "{{ .Values.resources.limits.memory | replace "Mi" "" }}"
        - name: ACTIVEMQ_BROKER_NAME
          value: "{{ template "activemq.fullname" . }}"
        - name: ACTIVEMQ_ADMIN_LOGIN
          valueFrom:
            secretKeyRef:
              name: {{ default (printf "%s-brokersecret" (include "content-services.shortname" $)) $.Values.adminUser.existingSecretName }}
              key: BROKER_USERNAME
        - name: ACTIVEMQ_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ default (printf "%s-brokersecret" (include "content-services.shortname" $)) $.Values.adminUser.existingSecretName }}
              key: BROKER_PASSWORD
        {{- if and (.Values.global.elasticAPM) (.Values.global.elasticAPM.enabled) }}
        - name: ELASTIC_APM_SERVER_URLS
          value: {{ .Values.global.elasticAPM.containers.env.serverUrls }}
        - name: ELASTIC_APM_SERVICE_NAME
          value: "activemq"
        - name: ELASTIC_APM_APPLICATION_PACKAGES
          value: com.alfresco,org.alfresco,nl.amsterdam,org.apache,org.fusesource,org.jasypt,org.slf4j,org.springframework,com.sun
        - name: ELASTIC_APM_ENVIRONMENT
          value: {{ .Values.global.elasticAPM.containers.env.environment }}
        - name: ELASTIC_APM_LOG_LEVEL
          value: {{ .Values.global.elasticAPM.containers.env.logLevel }}
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.elasticAPM.containers.env.secretToken.name }}
              key: {{ .Values.global.elasticAPM.containers.env.secretToken.key }}
        - name: JAVA_TOOL_OPTIONS
          value: {{ .Values.global.elasticAPM.containers.env.javaToolOptions }}
        {{- end }}
        ports:
        - name: stomp
          containerPort: {{ .Values.services.broker.ports.internal.stomp | default 61613 }}
        - name: openwire
          containerPort: {{ .Values.services.broker.ports.internal.openwire | default 61616 }}
        - name: amqp
          containerPort: {{ .Values.services.broker.ports.internal.amqp | default 5672 }}
        - name: web-console
          containerPort: {{ .Values.services.webConsole.ports.internal.webConsole | default 8161 }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.services.broker.ports.internal.openwire | default 61616 }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.services.broker.ports.internal.openwire | default 61616 }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          - name: data
            mountPath: {{ .Values.persistence.data.mountPath }}
            subPath: {{ .Values.persistence.data.subPath }}
          {{- if and (.Values.global.elasticAPM) (.Values.global.elasticAPM.enabled) }}
          - name: {{ .Values.global.elasticAPM.containers.volumeMounts.name }}
            mountPath: {{ .Values.global.elasticAPM.containers.volumeMounts.mountPath }}
          {{- end }}
      {{- if and (.Values.global.elasticAPM) (.Values.global.elasticAPM.enabled) }}
      initContainers:
        - name: elastic-java-agent
          image: {{ .Values.global.elasticAPM.initContainers.image }}
          volumeMounts:
          - mountPath: {{ .Values.global.elasticAPM.initContainers.volumeMounts.mountPath }}
            name: {{ .Values.global.elasticAPM.initContainers.volumeMounts.name }}
          command: ['cp', '-v', '/usr/agent/elastic-apm-agent.jar', '/elastic/apm/agent']
      {{- end }}
      volumes:
        {{- include "data_volume" .Values | nindent 8 }}
        {{- if and (.Values.global.elasticAPM) (.Values.global.elasticAPM.enabled) }}
        - name: elastic-apm-agent
          emptyDir: {}
        {{- end }}
{{- end }}
